modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/TelepathicGrunt/Blame/issues" #optional
license="GNU Lesser General Public License v3.0"

[[mods]] #mandatory
modId="blame" #mandatory
version="${version}" #mandatory
displayName="Blame!" #mandatory
logoFile="blame_icon.png" #optional
authors="TelepathicGrunt" #optional
description='''
Crashing due to a feature or structure from a mod? Don't worry!
This mod will find exactly which feature/structure and biome the crash is occurring from!

TIME TO PLACE SOME BLAME!!!
'''